### PR TITLE
feat: social bar

### PR DESCRIPTION
**Pull request by ahmaxed**

### CODE REVIEW

**Comment by ahmaxed** [comment]
the social icon bar is still the full width of the feed because it also appear at the end of the article content and act as a divider. having them in another size would look strange. 

they change background color on hover and select. ( to border color)

twitter will include author handle if author object has twitter.

the floating nav bar and progress bar are removed.

Screen Shot 2019-06-19 at 7 19 10 PM
Screen Shot 2019-06-19 at 7 19 43 PM

**Review by raisedadead — CHANGES_REQUESTED** [review]
Use white for the color on hover.

image

**Comment by raisedadead** [comment]
Also, make sure that the brand guidelines are followed with respect to twitter and facebook. I am sure we haven't gotten it wrong, but just double check.

**Review by raisedadead — CHANGES_REQUESTED** [review]
image

`@mention` required for authors?

**Comment by ahmaxed** [comment]
Changed the icons and spacing according to fb,twitter guidelines;
Changed items colors on hover;

The at mention works on my side. 
could you try it with another author account or your personal account.

Screen Shot 2019-06-20 at 11 18 56 AM

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
