### PR TITLE
fix(Search): align magnifying glass to position in root

### PR DESCRIPTION
**Pull request by AshNaz87**
Attempt at fixing the UI issue
Screenshot 2020-04-06 at 21 18 49

### CODE REVIEW

**Comment by AshNaz87** [comment]
Hopefully can close issue #37778 in website repo

**Comment by ahmaxed** [comment]
Thanks for the pr. Were you able to re-produce the magnifying glass misalignment issue on your side?

**Comment by AshNaz87** [comment]
Hi @ahmadabdolsaheb 

Yes, I was

**Comment by ahmaxed** [comment]
Thanks, for confirming.

**Comment by ahmaxed** [comment]
Are you running on a specific setup that let you see the issue? I am trying to reproduce the issue first so I could confirm the pr is resolving the issue.

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb 

I used the Ghost CLI. Was a little tricky to set up.

Want to discuss on Gitter?

**Comment by ahmaxed** [comment]
sure.

**Comment by ahmaxed** [comment]
@AshNaz87, I think changing width of search-input caused that, but not sure.

image

**Comment by ahmaxed** [comment]
Note: the width of the suggestions list should we as wide as the input.

**Comment by raisedadead** [comment]
Bump.

**Comment by AshNaz87** [comment]
Closed as I've created another PR for this

**Pull request closed without merging**
