### PR TITLE
feat: Conditionally render comments on pages

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Move comments script to its own file and conditionally render comments section on pages if it doesn't have the '#Disable Comments' internal tag

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM. 

And just to make sure, how are we handling not showing the tag itself on the news UI? I do not mean just the article view but other views that could/will display the tags?

**Comment by scissorsneedfoodtoo** [comment]
According to the [docs](https://ghost.org/docs/concepts/tags/#internal-tag), internal tags aren't visible to the public. 

Tags aren't shown on pages, so we don't have to worry about the Disable Comments tag there. While it's possible for an author to select it as a tag for their post, it won't be shown by the theme in the article view. There's also no tag page for internal tags, and going to `https://www.freecodecamp.org/news/tag/disable-comments` will show a 404.

**Comment by raisedadead** [comment]
Perfect.

**Comment by raisedadead** [comment]
Please deploy.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, deploying now. Will leave a comment explaining the new tag in https://github.com/freeCodeCamp/freeCodeCamp/issues/36809 before closing the issue.

**Pull request merged**
