### PR TITLE
Fixed Pagination for loading more articles on the Tag Page

### PR DESCRIPTION
**Pull request by sunnyssr**
Here is the fix for pagination on Tag Page. Reference to the issue:
#55
@ahmadabdolsaheb

### CODE REVIEW

**Comment by sunnyssr** [comment]
Here is the video in reference to that: 
https://vimeo.com/352706046

**Comment by ahmaxed** [comment]
@sunnyssr, Thanks for creating a new PR, attaching the video. 

Since some tags pages usually have a shorter list of articles comparing to the main page, the read more button would also be rendered conditionally only when necessary. 

For example if a tag only has five articles, showing the button is not necessary.

I was wondering if you would be interested in amending this functionality to this pr so we could ship it asap.

for a similar solution please see this logic:
https://github.com/freeCodeCamp/news-theme/blob/26fe3b391543b5c7b0e4d5639e8fda0a717469ce/search-results.hbs#L142

Ideally we need to grab the number of posts in one tag and render the button conditionally.
by default we are loading 25 post on the first load.
so if there are less than 25 posts in a tag, showing the button is not necessary.

Thank you

**Comment by sunnyssr** [comment]
@ahmadabdolsaheb 
I would do it within one day or two. Thanks for highlighting the issue.

**Comment by sunnyssr** [comment]
@ahmadabdolsaheb 
Done! There would be no button in case there is no next link in pagination.
Thank you

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmaxed** [comment]
Thanks @sunnyssr. I am sure developer news readers and authors will find this feature very useful

**Pull request merged**
